[hab]
plan_path = "components/hab"
paths = [
  "components/builder-api-client/*",
  "components/core/*",
  "components/common/*",
  "components/http-client/*",
  "components/sup-client/*",
  "components/sup-protocol/*",
]

[hab-backline]
plan_path = "components/backline"

[hab-bintray-publish]
plan_path = "components/bintray-publish"

[hab-launcher]
plan_path = "components/launcher/habitat"
paths = [
  "components/core/*",
  "components/common/*",
  "components/launcher/*",
  "components/launcher-protocol/*",
  "support/ci/builder-base-plan.sh",
]

[hab-plan-build]
plan_path = "components/plan-build"

[hab-plan-build-ps1]
plan_path = "components/plan-build-ps1"

[hab-studio]
plan_path = "components/studio"

[hab-sup]
plan_path = "components/sup"
paths = [
  "components/builder-api-client/*",
  "components/butterfly/*",
  "components/common/*",
  "components/core/*",
  "components/hab/*",
  "components/launcher-client/*",
  "components/sup-protocol/*",
]

[hab-pkg-aci]
plan_path = "components/pkg-aci"

[hab-pkg-export-docker]
plan_path = "components/pkg-export-docker"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*",
]

[hab-pkg-export-kubernetes]
plan_path = "components/pkg-export-kubernetes"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
]

[hab-pkg-export-helm]
plan_path = "components/pkg-export-helm"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
  "components/pkg-export-kubernetes/*",
]

[hab-pkg-export-tar]
plan_path = "components/pkg-export-tar"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*",
]

[hab-pkg-cfize]
plan_path = "components/pkg-cfize"
paths = [
  "components/pkg-export-docker/*"
]

[hab-pkg-mesosize]
plan_path = "components/pkg-mesosize"
